### PR TITLE
Add AppDelegate example in GRDBQueryKey's reportIssue comment

### PR DESCRIPTION
**Pull request by acosmicflamingo**
Figure others may stumble upon the issue I found myself in  when using GRDB in UIKit. Based off Stephen's suggestion in the Slack channel: https://pointfreecommunity.slack.com/archives/C04KQQ7NXHV/p1733690546509319?thread_ts=1733637497.493979&cid=C04KQQ7NXHV

### CODE REVIEW

**Review by stephencelis — COMMENTED** [review]
Rather than make the reported issue any longer, what do you think of including a link to documentation that contains more information?

**Comment by acosmicflamingo** [comment]
That sounds good! Where would the link go? Some documentation of `swift-dependencies` that I can create?

**Comment by stephencelis** [comment]
I think the documentation of `prepareDependencies` is a good spot. Going to close the PR on this end for now, but thanks for bringing it up!

**Comment by acosmicflamingo** [comment]
Sure! Right in the "important" block?
image

**Comment by stephencelis** [comment]
@acosmicflamingo I don't think it needs to be in a callout block. It can just be an example of usage in SwiftUI vs. UIKit with code blocks.

**Comment by acosmicflamingo** [comment]
I created two PRs that incorporate your suggestions:
- https://github.com/pointfreeco/swift-dependencies/pull/316
- https://github.com/pointfreeco/swift-sharing/pull/35

I imagine this is the way you envisioned it?

**Pull request closed without merging**
