### PR TITLE
Support Hashable

### PR DESCRIPTION
**Pull request by Mx-Iris**

### CODE REVIEW

**Comment by mbrandonw** [comment]
Hi @Mx-Iris, thanks for the PR, but this is something that we actually want to specifically forbid. We would even provide an [unavailable conformance](https://github.com/pointfreeco/swift-sharing/blob/e780420f8c52f80c8673be6707396fd5ca9bd650/Sources/Sharing/Shared.swift#L425-L430) to `Hashable`, but due to bugs in the Swift compiler this can be dangerous to do.

While `Shared` is defined as a struct it is in fact very reference-y. This makes it dangerous to naively make it `Hashable` based on the data it holds. And note that `@State` from SwiftUI has the same problem, and also does not conform to `Hashable`.

**Comment by Mx-Iris** [comment]
@mbrandonw About Hashable conformance and support Codable for AppStorageKey should be explained in the README to prevent others from submitting similar PRs again.

**Comment by mbrandonw** [comment]
Hi @Mx-Iris, we already have this [documented](https://swiftpackageindex.com/pointfreeco/swift-sharing/main/documentation/sharing/gotchas) and that article is linked to from the readme. I'm not sure people are necessarily going to read the full readme in order to find out this information. 

Ideally the Swift bug will be fixed so that we can provide an unavailable conformance that makes it impossible for others to create their own conformances.

**Comment by Mx-Iris** [comment]
Hi @mbrandonw, I think we can add this link to the README to remind people.

**Comment by mbrandonw** [comment]
The link is already present in the readme:

image

I just think that no matter what we message in the readme it is going to be missed by people wanting to contribute.

**Comment by Mx-Iris** [comment]
I'm sorry I didn't notice it.

**Pull request closed without merging**
